language: android
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-27"

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

script: ./gradlew build