language: android
android:
  components:
    - tools
    - build-tools-26.0.1
    - android-26
    - add-on
    - extra
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - chmod +x .buildscript/deploy_snapshot.sh

after_success:
  - .buildscript/deploy_snapshot.sh

script: ./gradlew build